# Generated by Django 3.1.7 on 2021-03-20 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_auto_20210313_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Изображение продукта'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_count', models.IntegerField(verbose_name='Количество')),
                ('cost', models.FloatField(verbose_name='Сумма')),
                ('order_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Код заказа')),
                ('date_order', models.DateTimeField(auto_now=True, verbose_name='Время и дата заказа')),
                ('accepted', models.BooleanField(default=False, verbose_name='Статус заказа')),
                ('product_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Продукт')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
